// La Forêt Enchantée — bibliothèque 2026
const state={view:'library',display:localStorage.getItem('forestDisplay')||'grid',categoryId:null,query:'',categories:[],subcategories:[],audios:[],currentAudio:null,queue:[]};
const player=new Audio();player.preload='metadata';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sameId=(a,b)=>String(a??'')===String(b??'');
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function formatDuration(seconds){if(!Number.isFinite(Number(seconds)))return'—';const v=Math.max(0,Math.floor(Number(seconds)));return`${Math.floor(v/60)}:${String(v%60).padStart(2,'0')}`;}
function categoryFor(audio){return state.categories.find(c=>sameId(c.id,audio.category_id));}
function subcategoryFor(audio){return state.subcategories.find(s=>sameId(s.id,audio.subcategory_id));}
function imageUrl(audio){return audio.image_path?getPublicUrl('images',audio.image_path):'';}
function audioUrl(audio){return audio.audio_path?getPublicUrl('audios',audio.audio_path):'';}

document.addEventListener('DOMContentLoaded',async()=>{wireInterface();await loadData();render();});
async function loadData(){const main=$('#main-content');try{const[cats,subs,auds]=await Promise.all([dbClient.from('categories').select('*').order('name'),dbClient.from('subcategories').select('*').order('name'),dbClient.from('audios').select('*').order('created_at',{ascending:false})]);const error=cats.error||subs.error||auds.error;if(error)throw error;state.categories=cats.data??[];state.subcategories=subs.data??[];state.audios=auds.data??[];}catch(error){console.error(error);main.innerHTML='<div class="empty-state"><strong>Impossible de charger la bibliothèque</strong><span>Vérifie la connexion puis recharge la page.</span></div>';}}
function wireInterface(){
  $$('.nav-button').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;state.categoryId=null;state.query='';$('#search-input').value='';$('#clear-search').hidden=true;render();}));
  const search=$('#search-input');search.addEventListener('input',()=>{state.query=search.value.trim();$('#clear-search').hidden=!state.query;render();});
  $('#clear-search').addEventListener('click',()=>{search.value='';state.query='';$('#clear-search').hidden=true;search.focus();render();});
  $('#grid-view').addEventListener('click',()=>setDisplay('grid'));$('#list-view').addEventListener('click',()=>setDisplay('list'));
  $('#play-pause').addEventListener('click',togglePlay);$('#prev-track').addEventListener('click',()=>stepTrack(-1));$('#next-track').addEventListener('click',()=>stepTrack(1));
  $('#player-progress').addEventListener('input',e=>{if(Number.isFinite(player.duration))player.currentTime=Number(e.target.value);});$('#player-volume').addEventListener('input',e=>player.volume=Number(e.target.value));
  player.addEventListener('play',updatePlayerState);player.addEventListener('pause',updatePlayerState);player.addEventListener('loadedmetadata',updateProgress);player.addEventListener('timeupdate',updateProgress);player.addEventListener('ended',()=>stepTrack(1));
}
function setDisplay(display){state.display=display;localStorage.setItem('forestDisplay',display);render();}
function filteredAudios(){let result=[...state.audios];if(state.view==='recent')result=result.slice(0,18);if(state.categoryId)result=result.filter(audio=>sameId(audio.category_id,state.categoryId));if(state.query){const needle=state.query.toLocaleLowerCase('fr');result=result.filter(audio=>{const category=categoryFor(audio)?.name??'',sub=subcategoryFor(audio)?.name??'';return[audio.title,audio.description,category,sub].some(v=>(v??'').toLocaleLowerCase('fr').includes(needle));});}return result;}
function render(){if(!state.audios.length&&!state.categories.length)return;updateNavigation();updateHeader();renderFilters();const main=$('#main-content');if(state.view==='categories'&&!state.query){renderCategories(main);return;}const audios=filteredAudios();if(!audios.length){main.innerHTML='<div class="empty-state"><strong>Aucun contenu trouvé</strong><span>Essaie un autre mot ou enlève le filtre de catégorie.</span></div>';return;}state.queue=audios;main.innerHTML=state.display==='list'?renderList(audios):renderGrid(audios);bindMediaActions(main);}
function updateNavigation(){$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#grid-view').classList.toggle('active',state.display==='grid');$('#list-view').classList.toggle('active',state.display==='list');$('#grid-view').setAttribute('aria-pressed',String(state.display==='grid'));$('#list-view').setAttribute('aria-pressed',String(state.display==='list'));}
function updateHeader(){const titles={library:['Médiathèque personnelle','Votre forêt sonore','Choisissez une histoire, lancez-la immédiatement et continuez à explorer sans interrompre l’écoute.'],recent:['À reprendre et découvrir','Récemment ajoutés','Les derniers contenus publiés, directement accessibles.'],categories:['Explorer','Toutes les catégories','Parcourez la collection par univers sonore.'],all:['Bibliothèque','Tous les audios','Une vue exhaustive, idéale pour retrouver rapidement un contenu précis.']};let[eyebrow,title,subtitle]=titles[state.view]??titles.library;if(state.query){eyebrow='Recherche';title=`« ${state.query} »`;subtitle='Résultats dans les titres, descriptions et catégories.';}$('#page-eyebrow').textContent=eyebrow;$('#page-title').textContent=title;$('#page-subtitle').textContent=subtitle;$('#content-stats').innerHTML=`<span class="stat-pill">${state.audios.length} audio${state.audios.length>1?'s':''}</span><span class="stat-pill">${state.categories.length} catégorie${state.categories.length>1?'s':''}</span>`;$('#toolbar').style.display=state.view==='categories'&&!state.query?'none':'';}
function renderFilters(){const chips=$('#category-chips');chips.innerHTML=`<button class="chip ${!state.categoryId?'active':''}" data-category="">Tout</button>`+state.categories.map(category=>{const count=state.audios.filter(audio=>sameId(audio.category_id,category.id)).length;return`<button class="chip ${sameId(state.categoryId,category.id)?'active':''}" data-category="${escapeHtml(category.id)}">${escapeHtml(category.name)} · ${count}</button>`;}).join('');chips.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{state.categoryId=chip.dataset.category||null;render();}));}
function renderCategories(container){const cards=state.categories.map(category=>{const count=state.audios.filter(audio=>sameId(audio.category_id,category.id)).length,subs=state.subcategories.filter(sub=>sameId(sub.category_id,category.id)).length;return`<button class="collection-card" data-category="${escapeHtml(category.id)}"><span class="collection-icon" aria-hidden="true">⌁</span><div class="collection-name">${escapeHtml(category.name)}</div><div class="collection-count">${count} histoire${count>1?'s':''}${subs?` · ${subs} sous-catégorie${subs>1?'s':''}`:''}</div></button>`;}).join('');container.innerHTML=cards?`<div class="collection-grid">${cards}</div>`:'<div class="empty-state"><strong>Aucune catégorie</strong><span>Les catégories créées dans l’administration apparaîtront ici.</span></div>';container.querySelectorAll('.collection-card').forEach(card=>card.addEventListener('click',()=>{state.view='all';state.categoryId=card.dataset.category;render();}));}
function renderGrid(audios){return`<div class="media-grid">${audios.map(audio=>{const category=categoryFor(audio)?.name??'Audio',cover=imageUrl(audio);return`<article class="media-card" data-id="${escapeHtml(audio.id)}" tabindex="0" aria-label="${escapeHtml(audio.title)}"><div class="cover-wrap">${cover?`<img class="cover-image" src="${escapeHtml(cover)}" alt="" loading="lazy">`:'<div class="cover-placeholder" aria-hidden="true">⌁</div>'}<button class="card-play" type="button" data-play="${escapeHtml(audio.id)}" aria-label="Lire ${escapeHtml(audio.title)}">▶</button></div><div class="media-meta"><div class="media-title">${escapeHtml(audio.title)}</div><div class="media-sub"><span>${escapeHtml(category)}</span><span>${formatDuration(audio.duration)}</span></div></div></article>`;}).join('')}</div>`;}
function renderList(audios){return`<div class="media-list">${audios.map(audio=>{const category=categoryFor(audio)?.name??'Audio',cover=imageUrl(audio);return`<article class="media-row" data-id="${escapeHtml(audio.id)}" tabindex="0">${cover?`<img class="row-cover" src="${escapeHtml(cover)}" alt="" loading="lazy">`:'<div class="row-cover cover-placeholder" aria-hidden="true">⌁</div>'}<div><div class="row-title">${escapeHtml(audio.title)}</div><div class="row-sub">${escapeHtml(category)}${audio.description?` · ${escapeHtml(audio.description).slice(0,90)}`:''}</div></div><div class="row-duration">${formatDuration(audio.duration)}</div><button class="row-play" type="button" data-play="${escapeHtml(audio.id)}" aria-label="Lire ${escapeHtml(audio.title)}">▶</button></article>`;}).join('')}</div>`;}
function bindMediaActions(container){container.querySelectorAll('[data-play]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();playById(button.dataset.play);}));container.querySelectorAll('[data-id]').forEach(item=>{const open=()=>location.href=`audio.html?id=${encodeURIComponent(item.dataset.id)}`;item.addEventListener('click',event=>{if(!event.target.closest('[data-play]'))open();});item.addEventListener('keydown',event=>{if(event.key==='Enter')open();});});}
function playById(id){const audio=state.audios.find(item=>sameId(item.id,id));if(!audio||!audio.audio_path)return;const same=state.currentAudio&&sameId(state.currentAudio.id,audio.id);if(!same){state.currentAudio=audio;player.src=audioUrl(audio);updateNowPlaying();}player.play().catch(error=>console.error('Lecture impossible',error));}
function togglePlay(){if(!state.currentAudio){const first=filteredAudios()[0];if(first)playById(first.id);return;}player.paused?player.play():player.pause();}
function stepTrack(direction){if(!state.queue.length)state.queue=filteredAudios();if(!state.queue.length)return;const current=state.currentAudio?state.queue.findIndex(item=>sameId(item.id,state.currentAudio.id)):-1,next=(current+direction+state.queue.length)%state.queue.length;playById(state.queue[next].id);}
function updateNowPlaying(){const audio=state.currentAudio;if(!audio)return;const mini=$('#mini-player');mini.classList.add('visible');mini.setAttribute('aria-hidden','false');$('#mini-title').textContent=audio.title;$('#mini-sub').textContent=categoryFor(audio)?.name??'La Forêt Enchantée';const cover=imageUrl(audio),coverEl=$('#mini-cover');coverEl.src=cover||'';coverEl.hidden=!cover;$('#details-link').href=`audio.html?id=${encodeURIComponent(audio.id)}`;updatePlayerState();}
function updatePlayerState(){const button=$('#play-pause');button.textContent=player.paused?'▶':'Ⅱ';button.setAttribute('aria-label',player.paused?'Lecture':'Pause');}
function updateProgress(){const progress=$('#player-progress'),duration=Number.isFinite(player.duration)?player.duration:Number(state.currentAudio?.duration||0);progress.max=duration||100;progress.value=Number.isFinite(player.currentTime)?player.currentTime:0;$('#elapsed').textContent=formatDuration(player.currentTime||0);$('#remaining').textContent=formatDuration(duration||0);}
